# Generated by Django 5.1.4 on 2026-01-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='Developer', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='In Progress', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='timeline',
            field=models.CharField(default='Ongoing', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('LG', 'Languages'), ('FW', 'Frameworks / Libraries'), ('AI', 'AI / ML'), ('DA', 'Data & Analytics'), ('DB', 'Databases')], max_length=2),
        ),
    ]
